# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B9fruW1UBm7Vg3HfhaHTfxuI5aPzAHmc
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

"""#Data processing"""

data=pd.read_csv('your data path')

data.head()

import pandas as pd
new_df = data.drop_duplicates(subset='number', keep='first')

new_df=new_df[["timestamp","number","gas_used","gas_limit","base_fee_per_gas"]]

new_df["base_fee_per_gas"] = new_df["base_fee_per_gas"]*10**-9

new_df.head()

new_df['gas_fraction'] = new_df['gas_used'] / new_df['gas_limit']

new_df['gas_target'] = (new_df['gas_used']-(new_df['gas_limit']/2)) / (new_df['gas_limit']/2)

org_data=np.array(new_df)

"""## 4 Machine learning medhods"""

from sklearn.model_selection import TimeSeriesSplit
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
import tensorflow as tf
import tensorflow.compat.v2 as tf
import matplotlib.pyplot as plt
import xgboost

import copy
x=[]
y=[]
for i in range(len(org_data)-10):
  base=org_data[i:i+11,4].tolist()
  gas_frc=org_data[i:i+10,5].tolist()
  now=np.concatenate((base, gas_frc),axis=0)
  now=now.tolist()
  x.append(now)
  y.append(org_data[i+10,6])
x=np.array(x)
y=np.array(y)

"""## Linear Regression"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import TimeSeriesSplit
from sklearn import linear_model
from sklearn.metrics import mean_squared_error

reg = linear_model.LinearRegression()
train_indices = []
validation_indices = []
test_indices = []
n_splits = 5
tss = TimeSeriesSplit(n_splits)
tss2 = TimeSeriesSplit(2)

for train_index, test_index in tss.split(x):
    x_train, x_test = x[train_index, :], x[test_index, :]
    y_train, y_test = y[train_index], y[test_index]
    for train_index, vali_index in tss2.split(x_train):
        x_train, x_vali = x[train_index, :], x[vali_index, :]
        y_train, y_vali = y[train_index], y[vali_index]
    train_indices.append(train_index)
    validation_indices.append(vali_index)
    test_indices.append(test_index)
    reg.fit(x_train, y_train)
    pred_reg = reg.predict(x_test)
    print(mean_squared_error(y_test, pred_reg))

offset = 0.1

plt.figure(figsize=(12, 6))
for i in range(n_splits):

    plt.scatter(train_indices[i], np.full_like(train_indices[i], i + 1) - offset, label=f'Fold {i + 1} - Train', marker='o', color='blue')

    plt.scatter(validation_indices[i], np.full_like(validation_indices[i], i + 1), label=f'Fold {i + 1} - Validation', marker='s', color='orange')

    plt.scatter(test_indices[i], np.full_like(test_indices[i], i + 1) + offset, label=f'Fold {i + 1} - Test', marker='^', color='green')

plt.yticks(range(1, n_splits + 1), labels=[f'Fold {i + 1}' for i in range(n_splits)], fontsize=14)
plt.xlabel('Data Index', fontsize=16)
plt.title('Position of Training, Validation, and Test Data', fontsize=18)
plt.legend(fontsize=10)
plt.show()

"""##DNN"""

from sklearn.model_selection import TimeSeriesSplit
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
reg = linear_model.LinearRegression()
train_indices = []
validation_indices = []
test_indices = []
n_splits = 5
result=[]
tss = TimeSeriesSplit(n_splits)
tss2 = TimeSeriesSplit(2)
for train_index, test_index in tss.split(x):
    tf.enable_v2_behavior()
    model_stability = tf.keras.models.Sequential([
        tf.keras.layers.Dense(128, activation = 'tanh',use_bias=True),
        tf.keras.layers.Dense(128, activation = 'linear',use_bias=True),
        tf.keras.layers.Dense(128, activation = 'tanh',use_bias=True),
        tf.keras.layers.Dense(1)
    ]
    )
    model_stability.compile(loss=tf.keras.losses.mean_squared_error,
                      optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
                      metrics=['mse'])

    training_callbacks = [
        tf.keras.callbacks.ReduceLROnPlateau(patience = 7, factor = 0.1, min_lr = 0.00001, verbose = 1),
        tf.keras.callbacks.EarlyStopping(patience = 12, restore_best_weights = True, verbose=1),
    ]

    x_train, x_test = x[train_index, :], x[test_index,:]
    y_train, y_test = y[train_index], y[test_index]
    for train_index, vali_index in tss2.split(x_train):
      x_train, x_vali = x[train_index, :], x[vali_index,:]
      y_train, y_vali = y[train_index], y[vali_index]
    train_indices.append(train_index)
    validation_indices.append(vali_index)
    test_indices.append(test_index)
    model_stability.fit(x_train, y_train, batch_size=64, epochs=100,callbacks=training_callbacks,validation_data=(x_vali,y_vali))
    pred_reg=model_stability.predict(x_test)
    result.append(mean_squared_error(y_test, pred_reg))
    print(mean_squared_error(y_test, pred_reg))

"""## XGBoost"""

from sklearn.model_selection import TimeSeriesSplit
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
reg = linear_model.LinearRegression()
train_indices = []
validation_indices = []
test_indices = []
n_splits = 5
result=[]
tss = TimeSeriesSplit(n_splits)
tss2 = TimeSeriesSplit(2)
for train_index, test_index in tss.split(x):
    x_train, x_test = x[train_index, :], x[test_index,:]
    y_train, y_test = y[train_index], y[test_index]
    for train_index, vali_index in tss2.split(x_train):
      x_train, x_vali = x[train_index, :], x[vali_index,:]
      y_train, y_vali = y[train_index], y[vali_index]
    train_indices.append(train_index)
    validation_indices.append(vali_index)
    test_indices.append(test_index)
    model = xgboost.XGBRegressor()
    model.fit(x_train, y_train)
    pred_reg=model.predict(x_test)
    result.append(mean_squared_error(y_test, pred_reg))
    print(mean_squared_error(y_test, pred_reg))

"""##Lstm"""

import copy
x=[]
y=[]
for i in range(len(org_data)-10):
  temp=[[0,0]]
  base=org_data[i:i+10,4:6].tolist()
  temp[0][0]=org_data[i+10,4]
  base.extend(temp)
  x.append(base)
  y.append(org_data[i+10,6])

x=np.array(x)
y=np.array(y)

from sklearn.model_selection import TimeSeriesSplit
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
reg = linear_model.LinearRegression()
n_splits = 5
result=[]
tss = TimeSeriesSplit(n_splits)
tss2 = TimeSeriesSplit(2)
for train_index, test_index in tss.split(x):
    x_train, x_test = x[train_index, :], x[test_index,:]
    y_train, y_test = y[train_index], y[test_index]
    for train_index, vali_index in tss2.split(x_train):
      x_train, x_vali = x[train_index, :], x[vali_index,:]
      y_train, y_vali = y[train_index], y[vali_index]
    train_indices.append(train_index)
    validation_indices.append(vali_index)
    test_indices.append(test_index)
    input_shape = (11, 2)

    model = tf.keras.Sequential([
        tf.keras.layers.LSTM(24, input_shape=input_shape, return_sequences=True),
        tf.keras.layers.LSTM(24, return_sequences=True),
        tf.keras.layers.LSTM(24),
        tf.keras.layers.Dense(100, activation='relu'),
        tf.keras.layers.Dense(1)
    ])

    training_callbacks = [
        tf.keras.callbacks.ReduceLROnPlateau(patience = 7, factor = 0.1, min_lr = 0.00001, verbose = 1),
        tf.keras.callbacks.EarlyStopping(patience = 12, restore_best_weights = True, verbose=1),
    ]
    model.compile(loss=tf.keras.losses.mean_squared_error,
                      optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
                      metrics=['mse'])

    model.fit(x_train, y_train, batch_size=64, epochs=100,callbacks=training_callbacks,validation_data=(x_vali,y_vali))
    pred_reg=model.predict(x_test)
    result.append(mean_squared_error(y_test, pred_reg))

"""#Training eporch for DNN"""

import copy
x=[]
y=[]
for i in range(len(org_data)-10):
  base=org_data[i:i+11,4].tolist()
  gas_frc=org_data[i:i+10,5].tolist()
  now=np.concatenate((base, gas_frc),axis=0)
  now=now.tolist()
  x.append(now)
  y.append(org_data[i+10,6])
x=np.array(x)
y=np.array(y)

from sklearn.model_selection import TimeSeriesSplit
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
tss = TimeSeriesSplit(n_splits=2)
for train_index, test_index in tss.split(x):
    x_train, x_test = x[train_index, :], x[test_index,:]
    y_train, y_test = y[train_index], y[test_index]

import tensorflow as tf
import matplotlib.pyplot as plt

model_stability = tf.keras.models.Sequential([
        tf.keras.layers.Dense(128, activation = 'tanh',use_bias=True),
        tf.keras.layers.Dense(128, activation = 'linear',use_bias=True),
        tf.keras.layers.Dense(128, activation = 'tanh',use_bias=True),
        tf.keras.layers.Dense(1)
    ]
    )
training_callbacks = [
    tf.keras.callbacks.ReduceLROnPlateau(patience=7, factor=0.1, min_lr=0.000001, verbose=1),
    tf.keras.callbacks.EarlyStopping(patience=12, restore_best_weights=True, verbose=1),
]
model_stability.compile(loss=tf.keras.losses.mean_squared_error,
                      optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
                      metrics=['mse'])


history = model_stability.fit(x_train, y_train, batch_size=512, epochs=100, callbacks=training_callbacks,validation_data=(x_test,y_test))

"""#Prediction using DNN"""

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')

plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training Curves')
plt.legend()
plt.show()

pred = model_stability.predict(x_test)

plt.plot(pred[0:100], label='pred gas used')
plt.plot(y_test[0:100], label='true gas used')
plt.title('Prediction')
plt.xlabel('0-100 datapoint')
plt.ylabel('gas used')
plt.legend()
plt.show()

"""#Prediction Using Linear Regression"""

reg = linear_model.LinearRegression()
reg.fit(x_train, y_train)
pred = reg.predict(x_test)

plt.plot(pred[0:100], label='pred gas used')
plt.plot(y_test[0:100], label='true gas used')
plt.title('Prediction of NFT-airdrip period using None-NFT-airdrop model')
plt.xlabel('0-100 datapoint')
plt.ylabel('gas used')
plt.legend()
plt.show()